CREATE TABLE IF NOT EXISTS listings (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  host_id INTEGER NOT NULL REFERENCES users(id),
  co_host_id INTEGER REFERENCES users(id),
  title TEXT NOT NULL,
  description TEXT,
  address TEXT NOT NULL,
  images JSONB  NOT NULL DEFAULT '[]'::JSONB,
  typeOfProperty type_of_property_enum NOT NULL DEFAULT 'Apartment',
  typeOfSpace type_of_space_enum NOT NULL DEFAULT 'Entire Place',
  extra_charges JSONB NOT NULL DEFAULT '{"cleaning": 0, "pets": 0, "aditionalGuest": 0}'::JSONB,
  size NUMERIC NOT NULL,
  price NUMERIC NOT NULL,
  currency TEXT NOT NULL,
  booking_nights_limits JSONB NOT NULL DEFAULT '{"min": 0, "max": 0}'::JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  fast_bookiing BOOLEAN DEFAULT FALSE,
  amenities JSONB NOT NULL DEFAULT '[]'::JSONB,
  rules JSONB NOT NULL DEFAULT '[]'::JSONB,
  security JSONB NOT NULL DEFAULT '[]'::JSONB,
  cancellation_policy INTEGER REFERENCES cancellation_policies(id),
  created_on TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_on TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);