INSERT INTO listing_amenities (name, description, icon) VALUES
  ('WiFi', 'High-speed wireless internet access available throughout the property', 'WifiRoundedIcon'),
  ('Air Conditioning', 'Climate control to keep you cool during your stay', 'AcUnitRoundedIcon'),
  ('Heating', 'Central heating to ensure a comfortable temperature', 'ThermostatRoundedIcon'),
  ('Beach access', 'Direct access to the beach for your enjoyment', 'BeachAccessRoundedIcon'),
  ('Pool', 'Outdoor or indoor swimming pool available for guests', 'PoolRoundedIcon'),
  ('Parking', 'On-site parking available for guests', 'LocalParkingRoundedIcon'),
  ('Washer/Dryer', 'In-unit washer and dryer for your convenience', 'LocalLaundryServiceRoundedIcon'),
  ('Pet Friendly', 'Pets are welcome at this property', 'PetsRoundedIcon'),
  ('Gym', 'Fitness center available for guest use', 'FitnessCenterRoundedIcon'),
  ('Conditioner', 'Hair conditioner provided for guest use', 'CleanHandsRoundedIcon'),
  ('Hot water', 'Access to hot water during your stay', 'HotTubRoundedIcon'),
  ('Pillows and blankets', 'Extra pillows and blankets provided', 'BedRoundedIcon'),
  ('Coffee maker', 'Coffee maker available in the kitchen', 'CoffeeMakerRoundedIcon'),
  ('Safe', 'In-room safe for securing valuables', 'LockRoundedIcon'),
  ('Shampoo', 'Hair shampoo provided for guest use', 'CleanHandsRoundedIcon'),
  ('kitchen', 'Fully equipped kitchen for preparing meals', 'KitchenRoundedIcon'),
  ('TV', 'Television available in the room', 'TvRoundedIcon'),
  ('Fire extinguisher', 'Fire extinguisher available for safety', 'FireExtinguisherRoundedIcon'),
  ('First aid kit', 'First aid kit available for emergencies', 'MedicalServicesRoundedIcon'),
  ('Smoke detector', 'Smoke detector installed for safety', 'SmokeDetectorRoundedIcon'),
  ('Carbon monoxide detector', 'Carbon monoxide detector installed for safety', 'DetectorRoundedIcon'),
  ('Hair dryer', 'Hair dryer provided for guest use', 'DryRoundedIcon'),
  ('Iron', 'Iron and ironing board available for guest use', 'IronRoundedIcon'),
  ('Microwave', 'Microwave available in the kitchen', 'MicrowaveRoundedIcon'),
  ('Plates and silverware', 'Plates and silverware provided for dining', 'RestaurantRoundedIcon')
ON CONFLICT (name) DO NOTHING;