name: ESLint & Test & Build (Monorepo)

on:
  push:
    branches:
      - main

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies for the web app
      - name: Install Dependencies (Web App)
        run: |
          if [ -f apps/web-app/package-lock.json ]; then
            cd apps/web-app && npm install
          fi

      # Install dependencies for each service in /services/*
      - name: Install Dependencies (Microservices)
        run: |
          for service in services/*; do
            if [ -f "$service/package-lock.json" ]; then
              echo "Installing dependencies for $service..."
              cd "$service" && npm install && cd ../..
            fi
          done

      # Run ESLint for Web App if changed
      - name: Run ESLint (Web App)
        run: |
          if git diff --name-only origin/main | grep -qE '^apps/web-app/'; then
            echo "Changes detected in web-app, running ESLint..."
            npx eslint apps/web-app --ext .js,.jsx,.ts,.tsx --max-warnings=0
          else
            echo "No changes in web-app, skipping ESLint."
          fi

      # Run ESLint for changed microservices
      - name: Run ESLint (Microservices)
        run: |
          for service in services/*; do
            if git diff --name-only origin/main | grep -qE "^$service/"; then
              echo "Changes detected in $service, running ESLint..."
              npx eslint "$service" --ext .js,.ts --max-warnings=0
            fi
          done
